bluelog/blueprints/admin.py
from flask import Blueprint, render_template, request, current_app, flash, redirect, url_for
from flask_login import login_required

from bluelog.extensions import db
from bluelog.forms import PostForm
from bluelog.models import Post, Category
from bluelog.utils import redirect_back

# ???这边的__name__是什么意思
admin_bp = Blueprint('admin', __name__)

@admin_bp.before_request
@login_required
def login_protect():
    pass

@admin_bp.route('/settings/')
def settings():
    return render_template('admin/settings.html')

@admin_bp.route('/post/new/', methods=['GET','POST'])
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        post = Post(title=title, body=body, category=category)
        db.session.add(post)
        db.session.commit()
        flash('Post created.','success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    return render_template('admin/new_post.html', form=form)

@admin_bp.route('/post/<int:post_id>/edit/', methods=['GET', 'POST'])
def edit_post(post_id):
    form = PostForm()
    post = Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.category = Category.query.get(form.category.data)
        db.session.commit()
        flash('Post updated.', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    form.title.data = post.title
    form.body.data = post.body
    form.category.data = post.category_id
    return render_template('admin/edit_post.html', form=form)

@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash('Post deleted.', 'success')
    return redirect(request.args.get('next'))

@admin_bp.route('/new_category/')
def new_category():
    return render_template('base.html')

@admin_bp.route('/post/manage')
def manage_post():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page=page, per_page=current_app.config['BLUELOG_MANAGE_POST_PER_PAGE'])
    posts = pagination.items
    return render_template('admin/manage_post.html', pagination=pagination,
                           posts=posts)

@admin_bp.route('/manage_category/')
def manage_category():
    pass

@admin_bp.route('/manage_comment/')
def manage_comment():
    pass

bluelog/blueprints/blog.py
from flask import Blueprint, render_template, request, current_app, url_for, redirect

from bluelog.extensions import db
from bluelog.forms import CommentForm
from bluelog.models import Post, Category, Comment

blog_bp = Blueprint('blog', __name__)

@blog_bp.route('/', defaults={'page': 1})
@blog_bp.route('/page/<int:page>')
def index(page):
    # page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUELOG_POST_PER_PAGE']
    pagination =Post.query.order_by(Post.timestamp.desc()).paginate(page=page,per_page=per_page)
    posts = pagination.items
    return render_template('blog/index.html', posts=posts, pagination=pagination)

@blog_bp.route('/about/')
def about():
    return render_template('blog/about.html')

@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUELOG_POST_PER_PAGE']
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.
                                desc()).paginate(page=page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/category.html', category=category,
                           pagination=pagination, posts=posts)



@blog_bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUELOG_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post).order_by(Comment.timestamp.asc()).paginate(page=page,per_page=per_page)
    comments = pagination.items

    # 发表评论
    # if current_user.is_authenticated: # 如果用户已登录
    #     pass
    form = CommentForm()

    if form.validate_on_submit():
        author = form.author.data
        body = form.body.data
        comment = Comment(
            author=author, body=body, post=post
        )
        replied_id = request.args.get('reply')
        if replied_id: # 如果URL中reply查询参数存在， 那么说明是回复
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('.show_post', post_id=post_id))
    return render_template('blog/post.html', post=post, pagination=pagination, form=form, comments=comments)

@blog_bp.route('/reply_comment/<int:comment_id>')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    return redirect(url_for('.show_post', post_id=comment.post_id, reply=comment_id,
                            author=comment.author) + '#comment-form')


@blog_bp.route('/testbase/')
def base():
    return render_template('base.html')

@blog_bp.route('/example/')
def example():
    return render_template('example.html')

bluelog/templates/blog/_post.html
{% if posts %}
    {% for post in posts %}
        <h3 class="text-primary"><a href="{{ url_for('.show_post', post_id=post.id) }}">
            {{ post.title }}
        </a></h3>
        <p>
            {{ post.body|striptags|truncate }}
            <small><a href="{{ url_for('.show_post', post_id=post.id) }}"></a></small>
        </p>
        <small>
            Comments: <a href="{{ url_for('.show_post', post_id=post.id) }}
                #comments">{{ post.comments|length }}</a>&nbsp;&nbsp;
            Category: <a href="{{ url_for('.show_category', category_id=post.category.id)
                }}">{{ post.category.name }}</a>
                <span class="float-right">{{ moment(post.timestamp).format('LL') }}</span>
        </small>
        {% if not loop.last %}
            <hr>
        {% endif %}

    {% endfor %}
{% endif %}

bluelog/templates/blog/_sidebar.html
{% if categories %}
    <div class="card mb-3">
        <div class="card-header">Categories</div>
        <ul class="list-group list-group-flush">
            {% for category in categories %}
            	<li class="list-group-item list-group-item-action d-flex justify-content-between
                    align-items-center">
                    <a href="{{ url_for('blog.show_category', category_id=category.id) }}">
                        {{ category.name }}
                    </a>
                    <span class="badge badge-primary badge-pill">{{ category.posts|length }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

bluelog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

bluelog/templates/blog/category.html
{% extends 'base.html' %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>{{ category.name }}</h1>
    </div>
    {% include 'blog/_post.html' %}

{% endblock %}

{% block footer %}
    <div class="page-footer">
        {{ render_pagination(pagination) }}
    </div>
{% endblock %}

bluelog/templates/blog/index.html
{% extends 'base.html' %}


{% block content %}
    <div class="row">
        <div class="col-md-8">
            {% include "blog/_post.html" %}
        </div>
        <div class="col-md-4 sidebar">
            {% include "blog/_sidebar.html" %}
        </div>
    </div>

{#    {% else %}#}
{#        <div class="tip">#}
{#            <h5>No posts yet.</h5>#}
{#            {% if current_user.is_authenticated %}#}
{#                <a href="{{ url_for('admin.new_post') }}">Write Now/a>#}
{#            {% endif %}#}
{#        </div>#}
{% endblock %}

{% block footer %}
    {% if posts %}
        <div class="page-footer">{{  render_pagination(pagination) }}</div>
    {% endif %}
{% endblock %}

bluelog/templates/blog/post.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <div class="page-header">
        <h1>{{ post.title }}</h1>
        <small>
            Category: <a href="{{ url_for('.show_category',category_id = post.category.id)
                }}">{{ post.category.name }}</a><br>
            Date: {{ moment(post.timestamp).format('LL') }}
        </small>
    </div>
    <div class="row">
        <div class="col-md-8">
            {{ post.body|safe }}
            <div class="comments" id="comments">
                <h3>{{ comments|length }}
                    <small>
                        <a href="{{ url_for('.show_post', post_id=post.id, page=pagination.pages or 1)
                                }}#comments">latest</a>
                    </small>
                </h3>
                {% if request.args.get('reply') %}
                    <div class="alert alert-dark">
                        Reply to <strong>{{ request.args.get('author') }}</strong>:
                        <a href="{{ url_for('.show_post', post_id=post.id) }}" class="float-right">Cancel</a>
                    </div>
                {% endif %}
                {% if comments %}
                	<ul class="list-group">
                        {% for comment in comments %}
                        	<li class="list-group-item list-group-action flex-column">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">
{#                                        <a href="{% if comment.site %}{{ comment.site }}#}
{#                                            {% else %}#{% endif %}"#}
{#                                                taget="_blank">#}
                                        <a href="#" target="_blank">
                                            {{ comment.author }}
                                        </a>
                                        {% if comment.replied %}
                                        	<span class="badge badge-primary">Reply</span>
                                        {% endif %}
                                    </h5>
                                    <small data-toggle="tooltip" data-placement="top" data-delag="500"
                                        data-timestamp="{{ comment.timestamp.strftime('%Y-
                                                %m-%dT%H:%M:%SZ') }}">
                                               {{ moment(comment.timestamp).fromNow()}}
                                    </small>
                                </div>
                                {% if comment.replied %}
                                	<p class="alert alert-dark reply-body">{{ comment.replied.author }}:
                                        <br>{{ comment.replied.body }}
                                    </p>
                                {% endif %}
                                <p class="mb-1">{{ comment.body }}</p>
                                    <div class="float-right">
                                        <a class ="btn btn-light btn-sm" href="{{ url_for('.reply_comment', comment_id=comment.id) }}">Reply</a>
                                    </div>
                            </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <div class="tip"><h5>No comments.</h5></div>
                {% endif %}
            </div>
            <div id="comment-form">
                    {{ render_form(form) }}
            </div>
            <br>
            {% if comments %}
            	{{ render_pagination(pagination, fragment='#comments') }}
            {% endif %}
        </div>

        <div class="col-md-4 sidebar">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

bluelog/templates/blog/reply_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>